---

- name: Creates directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ nginx_workdir }}"
    - "{{ nginx_workdir }}/htpasswd"
    - "{{ nginx_workdir }}/certs"
    - "{{ nginx_workdir }}/vhost.d"
    - "{{ nginx_workdir }}/html"

- name: Create an nginx-proxy container
  docker_container:
    name: nginx-proxy
    image: jwilder/nginx-proxy
    state: started
    restart_policy: on-failure
    restart_retries: 5
    restart: no
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "{{ nginx_workdir }}/htpasswd:/etc/nginx/htpasswd"
      - "{{ nginx_workdir }}/certs:/etc/nginx/certs"
      - "{{ nginx_workdir }}/vhost.d:/etc/nginx/vhost.d"
      - "{{ nginx_workdir }}/html:/usr/share/nginx/html"
      - /var/run/docker.sock:/tmp/docker.sock:ro

- name: Create an nginx-proxy-letsencrypt container
  docker_container:
    name: nginx-proxy-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    state: started
    restart_policy: on-failure
    restart_retries: 5
    restart: no
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
